name: rla_env

channels:
  - conda-forge

dependencies:
  - pinocchio
  - cppad
  - eigen
  - nlohmann_json
  - cmake
  - cxx-compiler
  - llvm
  - ninja
  - fmt
  - pkg-config
  - cpp-argparse
  - yaml-cpp
  - patch
  - git
